apiVersion: v1
kind: Service
metadata:
  name: {{ include "barme.fullname" . }}
  labels:
    {{- include "barme.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "barme.selectorLabels" . | nindent 4 }}
  ports:
    - name: s3
      port: {{ .Values.service.ports.s3 }}
      targetPort: s3
    - name: api
      port: {{ .Values.service.ports.api }}
      targetPort: api
    - name: cdn
      port: {{ .Values.service.ports.cdn }}
      targetPort: cdn
    - name: console
      port: {{ .Values.service.ports.console }}
      targetPort: console
